qcacmn: Fix unused function
error: unused function 'wmi_sar2_result_string' [-Werror,-Wunused-function]
 1364 | static const char *wmi_sar2_result_string(uint32_t result)
      |                    ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.

Signed-off-by: shygosh <shygosh@proton.me>